version: "3.8"
services:
  booking:
    container_name: booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
    command: ["pnpm", "start"]
    depends_on:
      - redis

  redis:
    image: redis 
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
